### ISSUE TITLE
Video Stream won't work (Zoom or Microsoft Teams

### ISSUE THREAD

**Issue by pqhcker** [dosdude1/macos-catalina-patcher#155] opened 2021-03-29 19:46 UTC
Hi... I found an issue with Microsoft Teams or Zoom. When I activate the camera so that the receiver can see me, everything works fine for the receiver, but as a sender, I can't see anyone's camera. It only shows black screen. Both audio and video work correctly

**Comment by SzosszeNET** [comment] 2021-03-31 09:18
Have you installed the patch? http://dosdude1.com/catalina/ bottom under FAQ, last point

**Comment by LogoiLab** [comment] 2021-04-28 21:11
duplicate of #89

**Closed by LogoiLab** 2021-04-28 21:11 UTC
Labels: duplicate

**Comment by kptkip** [comment] 2022-04-06 18:21
Another easy solution I found:
 https://forums.macrumors.com/attachments/tccplus-wrapper-hotfix-zip.903316/ 

- Download and run it
- Select which application you want to modify 
- Select "Microphone" and "Camera" (one procedure per app and device type)
- open the program twice and it works! 

I authorized chrome, slack and zoom for camera and mic :) 

Hope this helps people in the future
